# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Windows build

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - run: pnpm install --shamefully-hoist --no-frozen-lockfile
    - run: pnpm run build
    - run: pnpm run pack:win
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/*.msi"
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/*.appx"
